# Generated by Django 4.2.20 on 2025-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_role_alter_user_first_name_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
