# Generated by Django 4.2.20 on 2025-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fake_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
