# Generated by Django 4.2.20 on 2025-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_category_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('private', '仅作者和管理员'), ('public', '公开')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('private', '仅作者和管理员'), ('public', '公开')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.tag'),
        ),
    ]
