# Generated by Django 4.2.20 on 2025-04-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial_squashed_0006_tag_created_at_alter_post_tags_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='current_content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='is_create_approved',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='current_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='approved',
            new_name='is_create_approved',
        ),
        migrations.AddField(
            model_name='comment',
            name='edited_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_edit_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_edit_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
