# Generated by Django 4.2.20 on 2025-04-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_rename_content_comment_current_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='current_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='current_content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='edited_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
