# Generated by Django 4.2.20 on 2025-05-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='customer',
            new_name='author',
        ),
    ]
