# Generated by Django 4.2.20 on 2025-05-09 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demand', '0002_rename_customer_demand_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='demand.demand')),
            ],
            options={
                'verbose_name': '状态变更记录',
                'verbose_name_plural': '状态变更记录',
                'ordering': ['-changed_at'],
            },
        ),
    ]
