# Generated by Django 4.2.20 on 2025-05-09 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demand', '0003_demandstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='demand',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_demands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('accepted', '已受理'), ('in_progress', '处理中'), ('pending_review', '待反馈'), ('completed', '已完成'), ('rejected', '已拒绝'), ('on_hold', '已暂停'), ('cancelled', '已取消')], default='new', max_length=20, verbose_name='状态'),
        ),
    ]
