# Generated by Django 2.2.28 on 2025-04-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_auto_20250424_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/'),
        ),
    ]
