# Generated by Django 2.2.28 on 2025-04-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0003_auto_20250421_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='输入回复内容'),
        ),
    ]
